### PR TITLE
Add an explicit license file

### PR DESCRIPTION
**Pull request by JeromeMartinez**
We have a commitment with IETF but the provided rights about the document we write here are not explicit.

I suggest to have an explicit license file.
I use the [license for Matroska specs in IETF repo](https://github.com/ietf-wg-cellar/matroska-specification/blob/master/LICENSE.md), the Markdown version is an up to date version from [Creative-Commons-Markdown repo](https://github.com/idleberg/Creative-Commons-Markdown).

### CODE REVIEW

**Review by dericed — APPROVED** [review]

**Review by retokromer — APPROVED** [review]

**Comment by JeromeMartinez** [comment]
@michaelni; ok for merging this patch?

**Comment by michaelni** [comment]
Was every author asked if he agrees ?
or is there some implied agreement from something ?

**Comment by JeromeMartinez** [comment]
IMO @dericed, @michaelni and myself are the ones having together 99% of the content. I initiated the PR, @dericed approved it, so if you merge it an be trusted that people the most involved in the spec are fine with that :).
Additionally, I think we always communicated on openness and people involved are committed to openness, so it seems implied when people send patches (as we didn't explicitly asked when we sent the content to IETF).
In the remaining 1% there are @retokromer who already approved, and @dwbuiten & @pjotrek-b who are pinged now.

I suggest to wait a bit for the explicit approvals or concerns then merge if no issue raised.

**Comment by pjotrek-b** [comment]
+1 what Jérôme said :smile:
Approved.

**Review by dwbuiten — APPROVED** [review]
LGTM

**Review by pjotrek-b — APPROVED** [review]
LGTM.

**Comment by JeromeMartinez** [comment]
@michaelni as far as I know all other persons involved in the spec are approved this PR, any chance that this PR is merged before the IETF meeting?

**Comment by JeromeMartinez** [comment]
Greatly appreciated, thank you everyone!

**Pull request merged**
