### PR TITLE
update to version 03

### PR DESCRIPTION
**Pull request by dericed**

### CODE REVIEW

**Comment by dericed** [comment]
I suggest to merge this by the end of July 2nd so that a new draft can be sent to IETF's document tracker. If possible, let's resolve https://github.com/FFmpeg/FFV1/pull/68 first, but I suggest that 68 should not block this PR.

Also after merging this PR, please mark a new release.

**Comment by michaelni** [comment]
Should i wait with making a release a few hours to allow for more PRs ?

**Comment by JeromeMartinez** [comment]
IMO the pending PR/issues are not a blocker for IETF submission. No plan on my side for more updates.

**Comment by dericed** [comment]
@michaelni, could you also mark a release at https://github.com/FFmpeg/FFV1/releases.

**Comment by michaelni** [comment]
should that be called draft-niedermayer-cellar-ffv1-03 or draft-ietf-cellar-ffv1-03 ?
also what should i link to, last used https://datatracker.ietf.org/doc/draft-niedermayer-cellar-ffv1/02

**Comment by dericed** [comment]
Since it has become a Working Group document, it should be draft-ietf-cellar-ffv1-03.

**Comment by michaelni** [comment]
done, thx

**Comment by dericed** [comment]
Blerg, when I go to upload to the doc tracker. I get this error:
`Invalid revision (revision 00 is expected)`

I suppose the version numbering resets when the doc is moved to a working group document. I can send a new PR to create `draft-ietf-cellar-ffv1-00` but perhaps the commit of this PR should be dropped and the release should be renamed.

**Comment by michaelni** [comment]
should i create a draft-ietf-cellar-ffv1-00 release ? or can you check first if its accepted now ?

**Comment by dericed** [comment]
The xml is now accepted and in `The submission is pending approval by the group chairs.` status.

**Pull request closed without merging**
