### PR TITLE
Typos and cleanup

### PR DESCRIPTION
**Pull request by dericed**
minor changes: typos, grammar, formatting

### CODE REVIEW

**Comment by michaelni** [comment]
"Each frame is composed of 1 to 4 of the following colorspace planes: Y, Cb, Cr, Alpha"
This is true for YCbCr only

**Comment by dericed** [comment]
Right. I also think this section needs to be changed to reflect the hierarchy of frame>slice>plane, as currently this paragraph only refers to frame and plane, and then slice arrives later in the documentation without a good introduction.

**Comment by dericed** [comment]
I'm reviewing this again and have some questions:

- When the colorspace is RCT, are planes used? When I encode rgb24 with ffv1.v3 I only see one plane, but may be misinterpreting this.
- Re: "Each frame is composed of 1 to 4 ... planes". I'd like to be more specific. From this reading it seems like 2 planes is possible but that Cb should follow Y; however, are `ya` colorspaces possible (grayscale with alpha)?
- Is a 2 plane encoding possible?
- What is the meaning of `line` in this paragraph? The line count appears effected by the colorspace and possibly the chroma subsampling, but I'm not clear about this.
- Re: "since it is most likely that the RCT will immediately be converted to RGB during decoding" what other conversion is possible?

**Comment by michaelni** [comment]
i dont think pull requests are the right place for such questions, theres a IETF and a ffmpeg mailing list.
Here in the pull req basically only 2 people will see it

**Comment by dericed** [comment]
I moved the questions to an email here: https://mailarchive.ietf.org/arch/msg/cellar/nw5nwEmfnEEBu88QSOyJbsOQu5E. It appears the commits of this PR are already in the repository so I am closing the PR.

**Pull request closed without merging**
