### PR TITLE
use svg for math in non-text versions, drop non-rfc outputs

### PR DESCRIPTION
**Pull request by dericed**
This is a new attempt to add in svg images for the math to fully supersede https://github.com/FFmpeg/FFV1/pull/135. This is tested with mmark version 2.0.40, xml2rfc 2.23.1, xmlstarlet 1.6.1, pdfcrop v1.38, and pdf2svg 0.2.3.

This is tested on a Mac and provided this output:

```
ls ; mmark --version ; xml2rfc -V ; xmlstarlet --version ; pdfcrop --version
Makefile		README.md		ffv1.md			makesvg			rfc_backmatter.md	rfc_frontmatter.md
2.0.46
xml2rfc 2.23.1
1.6.1
compiled against libxml2 2.9.0, linked with 20904
compiled against libxslt 1.1.28, linked with 10129
pdfcrop 2012/11/02 v1.38
```

```
make
RFC rendering has been tested with mmark version 2.0.40, xml2rfc 2.23.1, xmlstarlet 1.6.1, pdfcrop v1.38, and pdf2svg 0.2.3, please ensure these are installed and recent enough.
bash makesvg
PDFCROP 1.38, 2012/11/02 - Copyright (c) 2002-2012 by Heiko Oberdiek.
==> 1 page written on `context.svg_cropped.pdf'.
PDFCROP 1.38, 2012/11/02 - Copyright (c) 2002-2012 by Heiko Oberdiek.
==> 1 page written on `quantizationtablesets.svg_cropped.pdf'.
PDFCROP 1.38, 2012/11/02 - Copyright (c) 2002-2012 by Heiko Oberdiek.
==> 1 page written on `rgb1.svg_cropped.pdf'.
PDFCROP 1.38, 2012/11/02 - Copyright (c) 2002-2012 by Heiko Oberdiek.
==> 1 page written on `rgb2.svg_cropped.pdf'.
PDFCROP 1.38, 2012/11/02 - Copyright (c) 2002-2012 by Heiko Oberdiek.
==> 1 page written on `samplediff.svg_cropped.pdf'.
PDFCROP 1.38, 2012/11/02 - Copyright (c) 2002-2012 by Heiko Oberdiek.
==> 1 page written on `rangebinaryvalues1.svg_cropped.pdf'.
PDFCROP 1.38, 2012/11/02 - Copyright (c) 2002-2012 by Heiko Oberdiek.
==> 1 page written on `rangebinaryvalues2.svg_cropped.pdf'.
PDFCROP 1.38, 2012/11/02 - Copyright (c) 2002-2012 by Heiko Oberdiek.
==> 1 page written on `rangebinaryvalues3.svg_cropped.pdf'.
PDFCROP 1.38, 2012/11/02 - Copyright (c) 2002-2012 by Heiko Oberdiek.
==> 1 page written on `rangebinaryvalues4.svg_cropped.pdf'.
PDFCROP 1.38, 2012/11/02 - Copyright (c) 2002-2012 by Heiko Oberdiek.
==> 1 page written on `rangebinaryvalues5.svg_cropped.pdf'.
PDFCROP 1.38, 2012/11/02 - Copyright (c) 2002-2012 by Heiko Oberdiek.
==> 1 page written on `rangebinaryvalues6.svg_cropped.pdf'.
PDFCROP 1.38, 2012/11/02 - Copyright (c) 2002-2012 by Heiko Oberdiek.
==> 1 page written on `rangebinaryvalues7.svg_cropped.pdf'.
PDFCROP 1.38, 2012/11/02 - Copyright (c) 2002-2012 by Heiko Oberdiek.
==> 1 page written on `statetransitiontable1.svg_cropped.pdf'.
PDFCROP 1.38, 2012/11/02 - Copyright (c) 2002-2012 by Heiko Oberdiek.
==> 1 page written on `statetransitiontable2.svg_cropped.pdf'.
PDFCROP 1.38, 2012/11/02 - Copyright (c) 2002-2012 by Heiko Oberdiek.
==> 1 page written on `initialstatedelta1.svg_cropped.pdf'.
PDFCROP 1.38, 2012/11/02 - Copyright (c) 2002-2012 by Heiko Oberdiek.
==> 1 page written on `initialstatedelta2.svg_cropped.pdf'.
cat rfc_frontmatter.md "ffv1.md" rfc_backmatter.md | grep -v "^RFC:" | grep -v "^SVGC" | grep -v "{V4}" |  sed "s|^RFC:||g;s|{V3}||g;s|SVGI:||g" > merged_rfchtml.md
mmark merged_rfchtml.md > draft-ietf-cellar-ffv1-08.xml
xml2rfc --html --v3 draft-ietf-cellar-ffv1-08.xml -o "draft-ietf-cellar-ffv1-08.html"
Parsing file draft-ietf-cellar-ffv1-08.xml
draft-ietf-cellar-ffv1-08.xml(3): Warning: Expected a 'docName' attribute in the <rfc/> element, but found none.
draft-ietf-cellar-ffv1-08.xml(3): Error: Expected <date> attribute "year" to be an integer, but found "undated"
draft-ietf-cellar-ffv1-08.xml(3): Error: Expected <date> attribute "year" to be an integer, but found "undated"
draft-ietf-cellar-ffv1-08.xml(3): Error: Expected <date> attribute "year" to be an integer, but found "undated"
draft-ietf-cellar-ffv1-08.xml(3): Error: Expected <date> attribute "year" to be an integer, but found "undated"
draft-ietf-cellar-ffv1-08.xml(3): Error: Expected <date> attribute "year" to be an integer, but found "undated"
Warning: Expected a numeric year, but found 'undated'
Warning: Expected a numeric year, but found 'undated'
Warning: Expected a numeric year, but found 'undated'
Warning: Expected a numeric year, but found 'undated'
Warning: Expected a numeric year, but found 'undated'
Created file draft-ietf-cellar-ffv1-08.html
bash makesvg
cat rfc_frontmatter.md "ffv1.md" rfc_backmatter.md | grep -v "^RFC:" | grep -v "^SVGC" | grep -v "{V3}" | sed "s|^RFC:||g;s|{V4}||g;s|SVGI:||g" > merged_rfchtml-v4.md
mmark merged_rfchtml-v4.md > draft-ietf-cellar-ffv1-v4-05.xml
xml2rfc --html --v3 draft-ietf-cellar-ffv1-v4-05.xml -o "draft-ietf-cellar-ffv1-v4-05.html"
Parsing file draft-ietf-cellar-ffv1-v4-05.xml
draft-ietf-cellar-ffv1-v4-05.xml(3): Warning: Expected a 'docName' attribute in the <rfc/> element, but found none.
draft-ietf-cellar-ffv1-v4-05.xml(3): Error: Expected <date> attribute "year" to be an integer, but found "undated"
draft-ietf-cellar-ffv1-v4-05.xml(3): Error: Expected <date> attribute "year" to be an integer, but found "undated"
draft-ietf-cellar-ffv1-v4-05.xml(3): Error: Expected <date> attribute "year" to be an integer, but found "undated"
draft-ietf-cellar-ffv1-v4-05.xml(3): Error: Expected <date> attribute "year" to be an integer, but found "undated"
draft-ietf-cellar-ffv1-v4-05.xml(3): Error: Expected <date> attribute "year" to be an integer, but found "undated"
Warning: Expected a numeric year, but found 'undated'
Warning: Expected a numeric year, but found 'undated'
Warning: Expected a numeric year, but found 'undated'
Warning: Expected a numeric year, but found 'undated'
Warning: Expected a numeric year, but found 'undated'
Created file draft-ietf-cellar-ffv1-v4-05.html
cat rfc_frontmatter.md "ffv1.md" rfc_backmatter.md | grep -v "^SVG" | grep -v "{V4}" | sed "s|^RFC:||g;s|{V3}||g" > merged_rfctxt.md
mmark merged_rfctxt.md > draft-ietf-cellar-ffv1-08.xml
xml2rfc --v3 draft-ietf-cellar-ffv1-08.xml -o "draft-ietf-cellar-ffv1-08.txt"
Parsing file draft-ietf-cellar-ffv1-08.xml
draft-ietf-cellar-ffv1-08.xml(3): Warning: Expected a 'docName' attribute in the <rfc/> element, but found none.
draft-ietf-cellar-ffv1-08.xml(3): Error: Expected <date> attribute "year" to be an integer, but found "undated"
draft-ietf-cellar-ffv1-08.xml(3): Error: Expected <date> attribute "year" to be an integer, but found "undated"
draft-ietf-cellar-ffv1-08.xml(3): Error: Expected <date> attribute "year" to be an integer, but found "undated"
draft-ietf-cellar-ffv1-08.xml(3): Error: Expected <date> attribute "year" to be an integer, but found "undated"
draft-ietf-cellar-ffv1-08.xml(3): Error: Expected <date> attribute "year" to be an integer, but found "undated"
Warning: Expected a numeric year, but found 'undated'
Warning: Expected a numeric year, but found 'undated'
Warning: Expected a numeric year, but found 'undated'
Warning: Expected a numeric year, but found 'undated'
Warning: Expected a numeric year, but found 'undated'
Created file draft-ietf-cellar-ffv1-08.txt
cat rfc_frontmatter.md "ffv1.md" rfc_backmatter.md | grep -v "^SVG" | grep -v "{V3}" | sed "s|^RFC:||g;s|{V4}||g" > merged_rfctxt-v4.md
mmark merged_rfctxt-v4.md > draft-ietf-cellar-ffv1-v4-05.xml
xml2rfc --v3 draft-ietf-cellar-ffv1-v4-05.xml -o "draft-ietf-cellar-ffv1-v4-05.txt"
Parsing file draft-ietf-cellar-ffv1-v4-05.xml
draft-ietf-cellar-ffv1-v4-05.xml(3): Warning: Expected a 'docName' attribute in the <rfc/> element, but found none.
draft-ietf-cellar-ffv1-v4-05.xml(3): Error: Expected <date> attribute "year" to be an integer, but found "undated"
draft-ietf-cellar-ffv1-v4-05.xml(3): Error: Expected <date> attribute "year" to be an integer, but found "undated"
draft-ietf-cellar-ffv1-v4-05.xml(3): Error: Expected <date> attribute "year" to be an integer, but found "undated"
draft-ietf-cellar-ffv1-v4-05.xml(3): Error: Expected <date> attribute "year" to be an integer, but found "undated"
draft-ietf-cellar-ffv1-v4-05.xml(3): Error: Expected <date> attribute "year" to be an integer, but found "undated"
Warning: Expected a numeric year, but found 'undated'
Warning: Expected a numeric year, but found 'undated'
Warning: Expected a numeric year, but found 'undated'
Warning: Expected a numeric year, but found 'undated'
Warning: Expected a numeric year, but found 'undated'
Created file draft-ietf-cellar-ffv1-v4-05.txt
```

### CODE REVIEW

**Comment by dericed** [comment]
👋 @michaelni, does this PR work for you?

**Comment by michaelni** [comment]
Well, iam a bit split on this.
One side of me wants to ask for an alternative, a format with a GUI or WYSIWYG editor that allows editing this so people can actually contribute with ease so the specification is very accessible.
The other side finds the design brilliant but feels it needs to be documented so a person wanting to edit does not need to reverse engeneer how it works.
Either way the build system fails here and it does not provide usable debug information to fix, also loosing non rfc outputs suck

```
cat rfc_frontmatter.md "ffv1.md" rfc_backmatter.md | grep -v "^RFC:" | grep -v "^SVGC" | grep -v "{V4}" |  sed "s|^RFC:||g;s|{V3}||g;s|SVGI:||g" > merged_rfchtml.md
mmark merged_rfchtml.md > draft-ietf-cellar-ffv1-08.xml
xml2rfc --html --v3 draft-ietf-cellar-ffv1-08.xml -o "draft-ietf-cellar-ffv1-08.html"
Parsing file draft-ietf-cellar-ffv1-08.xml
draft-ietf-cellar-ffv1-08.xml(3): Warning: Expected a 'docName' attribute in the <rfc/> element, but found none.
draft-ietf-cellar-ffv1-08.xml(3): Error: Expected <date> attribute "year" to be an integer, but found "undated"
draft-ietf-cellar-ffv1-08.xml(3): Error: Expected <date> attribute "year" to be an integer, but found "undated"
draft-ietf-cellar-ffv1-08.xml(3): Error: Expected <date> attribute "year" to be an integer, but found "undated"
draft-ietf-cellar-ffv1-08.xml(3): Error: Expected <date> attribute "year" to be an integer, but found "undated"
draft-ietf-cellar-ffv1-08.xml(3): Error: Expected <date> attribute "year" to be an integer, but found "undated"
draft-ietf-cellar-ffv1-08.xml(231): Warning: No 'type' attribute value provided for <artwork>, cannot process source file:///home/michael/ffmpeg-git/ffv1/context.svg
draft-ietf-cellar-ffv1-08.xml(231): Warning: No image data found in source file:///home/michael/ffmpeg-git/ffv1/context.svg
draft-ietf-cellar-ffv1-08.xml(237): Warning: No 'type' attribute value provided for <artwork>, cannot process source file:///home/michael/ffmpeg-git/ffv1/quantizationtablesets.svg
draft-ietf-cellar-ffv1-08.xml(237): Warning: No image data found in source file:///home/michael/ffmpeg-git/ffv1/quantizationtablesets.svg
draft-ietf-cellar-ffv1-08.xml(282): Warning: No 'type' attribute value provided for <artwork>, cannot process source file:///home/michael/ffmpeg-git/ffv1/rgb1.svg
draft-ietf-cellar-ffv1-08.xml(282): Warning: No image data found in source file:///home/michael/ffmpeg-git/ffv1/rgb1.svg
draft-ietf-cellar-ffv1-08.xml(284): Warning: No 'type' attribute value provided for <artwork>, cannot process source file:///home/michael/ffmpeg-git/ffv1/rgb2.svg
draft-ietf-cellar-ffv1-08.xml(284): Warning: No image data found in source file:///home/michael/ffmpeg-git/ffv1/rgb2.svg
draft-ietf-cellar-ffv1-08.xml(304): Warning: No 'type' attribute value provided for <artwork>, cannot process source file:///home/michael/ffmpeg-git/ffv1/samplediff.svg
draft-ietf-cellar-ffv1-08.xml(304): Warning: No image data found in source file:///home/michael/ffmpeg-git/ffv1/samplediff.svg
draft-ietf-cellar-ffv1-08.xml(311): Warning: No 'type' attribute value provided for <artwork>, cannot process source file:///home/michael/ffmpeg-git/ffv1/rangebinaryvalues1.svg
draft-ietf-cellar-ffv1-08.xml(311): Warning: No image data found in source file:///home/michael/ffmpeg-git/ffv1/rangebinaryvalues1.svg
draft-ietf-cellar-ffv1-08.xml(312): Warning: No 'type' attribute value provided for <artwork>, cannot process source file:///home/michael/ffmpeg-git/ffv1/rangebinaryvalues2.svg
draft-ietf-cellar-ffv1-08.xml(312): Warning: No image data found in source file:///home/michael/ffmpeg-git/ffv1/rangebinaryvalues2.svg
draft-ietf-cellar-ffv1-08.xml(313): Warning: No 'type' attribute value provided for <artwork>, cannot process source file:///home/michael/ffmpeg-git/ffv1/rangebinaryvalues3.svg
draft-ietf-cellar-ffv1-08.xml(313): Warning: No image data found in source file:///home/michael/ffmpeg-git/ffv1/rangebinaryvalues3.svg
draft-ietf-cellar-ffv1-08.xml(314): Warning: No 'type' attribute value provided for <artwork>, cannot process source file:///home/michael/ffmpeg-git/ffv1/rangebinaryvalues4.svg
draft-ietf-cellar-ffv1-08.xml(314): Warning: No image data found in source file:///home/michael/ffmpeg-git/ffv1/rangebinaryvalues4.svg
draft-ietf-cellar-ffv1-08.xml(315): Warning: No 'type' attribute value provided for <artwork>, cannot process source file:///home/michael/ffmpeg-git/ffv1/rangebinaryvalues5.svg
draft-ietf-cellar-ffv1-08.xml(315): Warning: No image data found in source file:///home/michael/ffmpeg-git/ffv1/rangebinaryvalues5.svg
draft-ietf-cellar-ffv1-08.xml(316): Warning: No 'type' attribute value provided for <artwork>, cannot process source file:///home/michael/ffmpeg-git/ffv1/rangebinaryvalues6.svg
draft-ietf-cellar-ffv1-08.xml(316): Warning: No image data found in source file:///home/michael/ffmpeg-git/ffv1/rangebinaryvalues6.svg
draft-ietf-cellar-ffv1-08.xml(317): Warning: No 'type' attribute value provided for <artwork>, cannot process source file:///home/michael/ffmpeg-git/ffv1/rangebinaryvalues7.svg
draft-ietf-cellar-ffv1-08.xml(317): Warning: No image data found in source file:///home/michael/ffmpeg-git/ffv1/rangebinaryvalues7.svg
draft-ietf-cellar-ffv1-08.xml(373): Warning: No 'type' attribute value provided for <artwork>, cannot process source file:///home/michael/ffmpeg-git/ffv1/statetransitiontable1.svg
draft-ietf-cellar-ffv1-08.xml(373): Warning: No image data found in source file:///home/michael/ffmpeg-git/ffv1/statetransitiontable1.svg
draft-ietf-cellar-ffv1-08.xml(374): Warning: No 'type' attribute value provided for <artwork>, cannot process source file:///home/michael/ffmpeg-git/ffv1/statetransitiontable2.svg
draft-ietf-cellar-ffv1-08.xml(374): Warning: No image data found in source file:///home/michael/ffmpeg-git/ffv1/statetransitiontable2.svg
draft-ietf-cellar-ffv1-08.xml(1059): Warning: No 'type' attribute value provided for <artwork>, cannot process source file:///home/michael/ffmpeg-git/ffv1/initialstatedelta1.svg
draft-ietf-cellar-ffv1-08.xml(1059): Warning: No image data found in source file:///home/michael/ffmpeg-git/ffv1/initialstatedelta1.svg
draft-ietf-cellar-ffv1-08.xml(1060): Warning: No 'type' attribute value provided for <artwork>, cannot process source file:///home/michael/ffmpeg-git/ffv1/initialstatedelta2.svg
draft-ietf-cellar-ffv1-08.xml(1060): Warning: No image data found in source file:///home/michael/ffmpeg-git/ffv1/initialstatedelta2.svg
draft-ietf-cellar-ffv1-08.xml(231): Error: Expected ascii-art artwork for <artwork type="">, but found b'<artwork xmlns:xi="http://www.w3.org/2001/XInclude" src="file:///home/michael/ffmpeg-git/ffv1/context.svg" alt="svg" name="conte'...
draft-ietf-cellar-ffv1-08.xml(237): Error: Expected ascii-art artwork for <artwork type="">, but found b'<artwork xmlns:xi="http://www.w3.org/2001/XInclude" src="file:///home/michael/ffmpeg-git/ffv1/quantizationtablesets.svg" alt="sv'...
draft-ietf-cellar-ffv1-08.xml(282): Error: Expected ascii-art artwork for <artwork type="">, but found b'<artwork xmlns:xi="http://www.w3.org/2001/XInclude" src="file:///home/michael/ffmpeg-git/ffv1/rgb1.svg" alt="svg" name="rgb 1" a'...
draft-ietf-cellar-ffv1-08.xml(284): Error: Expected ascii-art artwork for <artwork type="">, but found b'<artwork xmlns:xi="http://www.w3.org/2001/XInclude" src="file:///home/michael/ffmpeg-git/ffv1/rgb2.svg" alt="svg" name="rgb 2" a'...
draft-ietf-cellar-ffv1-08.xml(304): Error: Expected ascii-art artwork for <artwork type="">, but found b'<artwork xmlns:xi="http://www.w3.org/2001/XInclude" src="file:///home/michael/ffmpeg-git/ffv1/samplediff.svg" alt="svg" name="co'...
draft-ietf-cellar-ffv1-08.xml(311): Error: Expected ascii-art artwork for <artwork type="">, but found b'<artwork xmlns:xi="http://www.w3.org/2001/XInclude" src="file:///home/michael/ffmpeg-git/ffv1/rangebinaryvalues1.svg" alt="svg" '...
draft-ietf-cellar-ffv1-08.xml(312): Error: Expected ascii-art artwork for <artwork type="">, but found b'<artwork xmlns:xi="http://www.w3.org/2001/XInclude" src="file:///home/michael/ffmpeg-git/ffv1/rangebinaryvalues2.svg" alt="svg" '...
draft-ietf-cellar-ffv1-08.xml(313): Error: Expected ascii-art artwork for <artwork type="">, but found b'<artwork xmlns:xi="http://www.w3.org/2001/XInclude" src="file:///home/michael/ffmpeg-git/ffv1/rangebinaryvalues3.svg" alt="svg" '...
draft-ietf-cellar-ffv1-08.xml(314): Error: Expected ascii-art artwork for <artwork type="">, but found b'<artwork xmlns:xi="http://www.w3.org/2001/XInclude" src="file:///home/michael/ffmpeg-git/ffv1/rangebinaryvalues4.svg" alt="svg" '...
draft-ietf-cellar-ffv1-08.xml(315): Error: Expected ascii-art artwork for <artwork type="">, but found b'<artwork xmlns:xi="http://www.w3.org/2001/XInclude" src="file:///home/michael/ffmpeg-git/ffv1/rangebinaryvalues5.svg" alt="svg" '...
draft-ietf-cellar-ffv1-08.xml(316): Error: Expected ascii-art artwork for <artwork type="">, but found b'<artwork xmlns:xi="http://www.w3.org/2001/XInclude" src="file:///home/michael/ffmpeg-git/ffv1/rangebinaryvalues6.svg" alt="svg" '...
draft-ietf-cellar-ffv1-08.xml(317): Error: Expected ascii-art artwork for <artwork type="">, but found b'<artwork xmlns:xi="http://www.w3.org/2001/XInclude" src="file:///home/michael/ffmpeg-git/ffv1/rangebinaryvalues7.svg" alt="svg" '...
draft-ietf-cellar-ffv1-08.xml(373): Error: Expected ascii-art artwork for <artwork type="">, but found b'<artwork xmlns:xi="http://www.w3.org/2001/XInclude" src="file:///home/michael/ffmpeg-git/ffv1/statetransitiontable1.svg" alt="sv'...
draft-ietf-cellar-ffv1-08.xml(374): Error: Expected ascii-art artwork for <artwork type="">, but found b'<artwork xmlns:xi="http://www.w3.org/2001/XInclude" src="file:///home/michael/ffmpeg-git/ffv1/statetransitiontable2.svg" alt="sv'...
draft-ietf-cellar-ffv1-08.xml(1059): Error: Expected ascii-art artwork for <artwork type="">, but found b'<artwork xmlns:xi="http://www.w3.org/2001/XInclude" src="file:///home/michael/ffmpeg-git/ffv1/initialstatedelta1.svg" alt="svg" '...
draft-ietf-cellar-ffv1-08.xml(1060): Error: Expected ascii-art artwork for <artwork type="">, but found b'<artwork xmlns:xi="http://www.w3.org/2001/XInclude" src="file:///home/michael/ffmpeg-git/ffv1/initialstatedelta2.svg" alt="svg" '...
Warning: Expected a numeric year, but found 'undated'
Warning: Expected a numeric year, but found 'undated'
Warning: Expected a numeric year, but found 'undated'
Warning: Expected a numeric year, but found 'undated'
Warning: Expected a numeric year, but found 'undated'
Not creating output file due to errors (see above)
```

**Comment by JeromeMartinez** [comment]
> One side of me wants to ask for an alternative, a format with a GUI or WYSIWYG editor that allows editing this so people can actually contribute with ease so the specification is very accessible.

I dream about such solution but I don't see a real possibility with the tool we currently have, and it was previously already complex, it is "just" a bit more complex with this patch.

In my opinion most of the spec is still easy to edit (Markdown, the most used format nowaday, with lot of WYSIWYG editor) and maths edition is already complex so not the first thing most people will touch (actually main issues we have with the spec are on the bitstream description, so the parts easy to edit), so I am in favor of this patch as an intermediate solution up to when someone finds a better solution.

**Comment by dericed** [comment]
Thanks @michaelni for the output. Could you also run `ls ; mmark --version ; xml2rfc -V ; xmlstarlet --version ; pdfcrop --version` and send me that output and perhaps email me the svg files that you generated?

**Comment by michaelni** [comment]
```
ls ; mmark --version ; xml2rfc -V ; xmlstarlet --version ; pdfcrop --version
context.svg                    draft-ietf-cellar-ffv1-v4-05.txt  initialstatedelta1.svg  makesvg               merged_rfctxt.md           rangebinaryvalues1.svg  rangebinaryvalues4.svg  rangebinaryvalues7.svg  rfc_frontmatter.md  samplediff.svg
draft-ietf-cellar-ffv1-08.txt  draft-ietf-cellar-ffv1-v4-05.xml  initialstatedelta2.svg  merged_rfchtml.md     merged_rfctxt-v4.md        rangebinaryvalues2.svg  rangebinaryvalues5.svg  README.md               rgb1.svg            statetransitiontable1.svg
draft-ietf-cellar-ffv1-08.xml  ffv1.md                           Makefile                merged_rfchtml-v4.md  quantizationtablesets.svg  rangebinaryvalues3.svg  rangebinaryvalues6.svg  rfc_backmatter.md       rgb2.svg            statetransitiontable2.svg
2.0.45
xml2rfc 2.23.1

compiled against libxml2 2.9.2, linked with 20903
compiled against libxslt 1.1.28, linked with 10128
pdfcrop 2012/11/02 v1.38

```
will email the svg files

**Comment by dericed** [comment]
Thanks @michaelni. Could you please retry with [mmark 2.0.48](https://github.com/mmarkdown/mmark/releases). The svg files match what I have on my side, but I do get the same error on my side with mmark 2.0.45.

Also IIUC the advantage of the non rfc outputs was the better representation of math, which is supported in the PR. Maintaining a method to produce an svg-math rfc, ascii-art rfc, and non-rfc pdf seems a bit too complex, so I propose removing the non-rfc output if the svg-math rfc can supersede the non-rfc output. Are there other advantages of the non-rfc output to consider?

**Comment by michaelni** [comment]
```
$ mmark --version
2.0.48
$ make
RFC rendering has been tested with mmark version 2.0.40, xml2rfc 2.23.1, xmlstarlet 1.6.1, pdfcrop v1.38, and pdf2svg 0.2.3, please ensure these are installed and recent enough.
bash makesvg
cat rfc_frontmatter.md "ffv1.md" rfc_backmatter.md | grep -v "^RFC:" | grep -v "^SVGC" | grep -v "{V4}" |  sed "s|^RFC:||g;s|{V3}||g;s|SVGI:||g" > merged_rfchtml.md
mmark merged_rfchtml.md > draft-ietf-cellar-ffv1-08.xml
xml2rfc --html --v3 draft-ietf-cellar-ffv1-08.xml -o "draft-ietf-cellar-ffv1-08.html"
Parsing file draft-ietf-cellar-ffv1-08.xml
draft-ietf-cellar-ffv1-08.xml(3): Error: Expected <date> attribute "year" to be an integer, but found "undated"
draft-ietf-cellar-ffv1-08.xml(3): Error: Expected <date> attribute "year" to be an integer, but found "undated"
draft-ietf-cellar-ffv1-08.xml(3): Error: Expected <date> attribute "year" to be an integer, but found "undated"
draft-ietf-cellar-ffv1-08.xml(3): Error: Expected <date> attribute "year" to be an integer, but found "undated"
draft-ietf-cellar-ffv1-08.xml(3): Error: Expected <date> attribute "year" to be an integer, but found "undated"
Warning: Expected a numeric year, but found 'undated'
Warning: Expected a numeric year, but found 'undated'
Warning: Expected a numeric year, but found 'undated'
Warning: Expected a numeric year, but found 'undated'
Warning: Expected a numeric year, but found 'undated'
Created file draft-ietf-cellar-ffv1-08.html
bash makesvg
cat rfc_frontmatter.md "ffv1.md" rfc_backmatter.md | grep -v "^RFC:" | grep -v "^SVGC" | grep -v "{V3}" | sed "s|^RFC:||g;s|{V4}||g;s|SVGI:||g" > merged_rfchtml-v4.md
mmark merged_rfchtml-v4.md > draft-ietf-cellar-ffv1-v4-05.xml
xml2rfc --html --v3 draft-ietf-cellar-ffv1-v4-05.xml -o "draft-ietf-cellar-ffv1-v4-05.html"
Parsing file draft-ietf-cellar-ffv1-v4-05.xml
draft-ietf-cellar-ffv1-v4-05.xml(3): Error: Expected <date> attribute "year" to be an integer, but found "undated"
draft-ietf-cellar-ffv1-v4-05.xml(3): Error: Expected <date> attribute "year" to be an integer, but found "undated"
draft-ietf-cellar-ffv1-v4-05.xml(3): Error: Expected <date> attribute "year" to be an integer, but found "undated"
draft-ietf-cellar-ffv1-v4-05.xml(3): Error: Expected <date> attribute "year" to be an integer, but found "undated"
draft-ietf-cellar-ffv1-v4-05.xml(3): Error: Expected <date> attribute "year" to be an integer, but found "undated"
Warning: Expected a numeric year, but found 'undated'
Warning: Expected a numeric year, but found 'undated'
Warning: Expected a numeric year, but found 'undated'
Warning: Expected a numeric year, but found 'undated'
Warning: Expected a numeric year, but found 'undated'
Created file draft-ietf-cellar-ffv1-v4-05.html
cat rfc_frontmatter.md "ffv1.md" rfc_backmatter.md | grep -v "^SVG" | grep -v "{V4}" | sed "s|^RFC:||g;s|{V3}||g" > merged_rfctxt.md
mmark merged_rfctxt.md > draft-ietf-cellar-ffv1-08.xml
xml2rfc --v3 draft-ietf-cellar-ffv1-08.xml -o "draft-ietf-cellar-ffv1-08.txt"
Parsing file draft-ietf-cellar-ffv1-08.xml
draft-ietf-cellar-ffv1-08.xml(3): Error: Expected <date> attribute "year" to be an integer, but found "undated"
draft-ietf-cellar-ffv1-08.xml(3): Error: Expected <date> attribute "year" to be an integer, but found "undated"
draft-ietf-cellar-ffv1-08.xml(3): Error: Expected <date> attribute "year" to be an integer, but found "undated"
draft-ietf-cellar-ffv1-08.xml(3): Error: Expected <date> attribute "year" to be an integer, but found "undated"
draft-ietf-cellar-ffv1-08.xml(3): Error: Expected <date> attribute "year" to be an integer, but found "undated"
Warning: Expected a numeric year, but found 'undated'
Warning: Expected a numeric year, but found 'undated'
Warning: Expected a numeric year, but found 'undated'
Warning: Expected a numeric year, but found 'undated'
Warning: Expected a numeric year, but found 'undated'
Created file draft-ietf-cellar-ffv1-08.txt
cat rfc_frontmatter.md "ffv1.md" rfc_backmatter.md | grep -v "^SVG" | grep -v "{V3}" | sed "s|^RFC:||g;s|{V4}||g" > merged_rfctxt-v4.md
mmark merged_rfctxt-v4.md > draft-ietf-cellar-ffv1-v4-05.xml
xml2rfc --v3 draft-ietf-cellar-ffv1-v4-05.xml -o "draft-ietf-cellar-ffv1-v4-05.txt"
Parsing file draft-ietf-cellar-ffv1-v4-05.xml
draft-ietf-cellar-ffv1-v4-05.xml(3): Error: Expected <date> attribute "year" to be an integer, but found "undated"
draft-ietf-cellar-ffv1-v4-05.xml(3): Error: Expected <date> attribute "year" to be an integer, but found "undated"
draft-ietf-cellar-ffv1-v4-05.xml(3): Error: Expected <date> attribute "year" to be an integer, but found "undated"
draft-ietf-cellar-ffv1-v4-05.xml(3): Error: Expected <date> attribute "year" to be an integer, but found "undated"
draft-ietf-cellar-ffv1-v4-05.xml(3): Error: Expected <date> attribute "year" to be an integer, but found "undated"
Warning: Expected a numeric year, but found 'undated'
Warning: Expected a numeric year, but found 'undated'
Warning: Expected a numeric year, but found 'undated'
Warning: Expected a numeric year, but found 'undated'
Warning: Expected a numeric year, but found 'undated'
Created file draft-ietf-cellar-ffv1-v4-05.txt
```

**Comment by michaelni** [comment]
about non rfc. Iam not sure how this interacts with future changes. As the document over time changed from something we can edit at will for a future version to now being always an rfc.
previously if we wanted to experiment with lets say some bayer coding we could turn it into a non rfc pdf. now it would be a rfc style text, are you sure this would not cause some confusion?

**Comment by michaelni** [comment]
i think nothing is blocking, i just wanted to better understand if this drop of non rfc could have some side effects

**Pull request merged**
