### PR TITLE
Miller FFV1 review

### PR DESCRIPTION
**Pull request by dericed**
responding to https://mailarchive.ietf.org/arch/msg/cellar/671YjBEqo-vdtrHdUebApfu7t_8

### CODE REVIEW

**Comment by michaelni** [comment]
Commit message should explain what is changed and why. Some of these commits use just 1 word. Also i think extenal references should be used carefully in commit messages. Who knows if these URLs will work in 10 years.

**Comment by dericed** [comment]
Any comments on the contents of the commits before I rewrite the messages?

**Comment by michaelni** [comment]
i didnt spot any issues in the content, of course i might spot some in conjuction with new messages or when i look a 2nd time

**Comment by dericed** [comment]
the commit messages are updated to be a bit more verbose, please re-review

**Comment by dericed** [comment]
nudge :)

**Pull request merged**
