### PR TITLE
Workaround for rfc2xml v2

### PR DESCRIPTION
**Pull request by dericed**
This adds workarounds for the expression of undated references as recommended by @mcr. The PR also replaces the <sourcecode> element with <artwork>, since sourcecode is an rfc2xml element and the processor behind the ietf upload tool does not process it correctly, but it results in the line breaks being stripped from the <sourcecode> element contents.

### CODE REVIEW

**Comment by michaelni** [comment]
This seems to break build here
```
make clean ; make
RFC rendering has been tested with mmark version 2.0.48, xml2rfc 2.23.1, xmlstarlet 1.6.1, pdfcrop v1.38, and pdf2svg 0.2.3, please ensure these are installed and recent enough.
rm -f ffv1.pdf ffv1-v4.pdf ffv1.html ffv1-v4.html draft-ietf-cellar-ffv1-* merged_*
RFC rendering has been tested with mmark version 2.0.48, xml2rfc 2.23.1, xmlstarlet 1.6.1, pdfcrop v1.38, and pdf2svg 0.2.3, please ensure these are installed and recent enough.
bash makesvg
cat rfc_frontmatter.md "ffv1.md" rfc_backmatter.md | grep -v "^AART:" | grep -v "^SVGC" | grep -v "{V4}" |  sed "s|^AART:||g;s|{V3}||g;s|SVGI:||g" > merged_rfchtml.md
mmark merged_rfchtml.md | sed 's|<date year="undated"></date>|<date>undated</date>|g;s|<sourcecode type="c">|<artwork type="ascii-art">|g;s|</sourcecode>|</artwork>|g' > draft-ietf-cellar-ffv1-09.xml
bash svg2src draft-ietf-cellar-ffv1-09.xml
xml2rfc --html --v3 "draft-ietf-cellar-ffv1-09.xml" -o "draft-ietf-cellar-ffv1-09.html"
Parsing file draft-ietf-cellar-ffv1-09.xml
draft-ietf-cellar-ffv1-09.xml(1793): Error: Did not expect text in element date content, at /rfc/back/references[2]/reference[2]/front/date
draft-ietf-cellar-ffv1-09.xml(1811): Error: Did not expect text in element date content, at /rfc/back/references[2]/reference[4]/front/date
draft-ietf-cellar-ffv1-09.xml(1872): Error: Did not expect text in element date content, at /rfc/back/references[2]/reference[12]/front/date
draft-ietf-cellar-ffv1-09.xml(1881): Error: Did not expect text in element date content, at /rfc/back/references[2]/reference[13]/front/date
draft-ietf-cellar-ffv1-09.xml(1890): Error: Did not expect text in element date content, at /rfc/back/references[2]/reference[14]/front/date
draft-ietf-cellar-ffv1-09.xml(3): Error: Invalid document before running preptool.
Cannot continue, quitting now
Makefile:24: recipe for target 'draft-ietf-cellar-ffv1-09.html' failed
make: *** [draft-ietf-cellar-ffv1-09.html] Error 1
```

**Comment by dericed** [comment]
What is your output for `xml2rfc --version`. I have version 2.30.0. I'm guessing, but from reading the change log, it seems that 2.24.0 or later is needed.

**Comment by dericed** [comment]
I see that our own docs require 2.23.1. I'm going to test with the latest xml2rfc and perhaps update the docs to that latest version.

**Comment by dericed** [comment]
I tested again on 2.30.0 and 2.32.0 and they produce the same output and the `<date>undated</date>` element as suggested by IETF works. Please run `pip install xml2rfc -U` to update xml2rfc and re-review.

**Comment by michaelni** [comment]
> What is your output for `xml2rfc --version`. I have version 2.30.0. I'm guessing, but from reading the change log, it seems that 2.24.0 or later is needed.

xml2rfc --version
xml2rfc 2.23.1

**Pull request merged**
