### PR TITLE
add Matroska mapping

### PR DESCRIPTION
**Pull request by dericed**

### CODE REVIEW

**Comment by dericed** [comment]
should match with https://github.com/Matroska-Org/matroska-specification/blob/master/codec_specs.md#v_ffv1

**Comment by JeromeMartinez** [comment]
I think that the "V_MS/VFW/FOURCC" part should not be there: content of the paragraph about the ConfigurationRecord position is already in the AVI part, and "V_MS/VFW/FOURCC" part in Matroska is for AVI compatibility.
Here, I see a mix of Matroska and AVI details in the same paragraph, not good.

I suggest that the 2nd paragprah of FFV1 in Matroska is removed, alternatively with the BITMAPINFOHEADER part as another PR about extending AVI part.

**Comment by dericed** [comment]
updated per @JeromeMartinez's comments, though I want to be sure that someone using this spec to interpret ffv1 in mkv, doesn't ignore all the legacy mkv with ffv1 in VFW

**Comment by michaelni** [comment]
Maybe you want to add some text mentioning VFW

**Pull request merged**
