### PR TITLE
bump to ffv1-11 and ffv1-v4-08

### PR DESCRIPTION
**Pull request by dericed**
I suggest a version bump so I can post a new version before the meeting today.

### CODE REVIEW

**Comment by retokromer** [comment]
@dericed Is the meeting today, not on the 22<sup>nd</sup>?

**Comment by michaelni** [comment]
should i still merge this or wait ?

**Comment by dericed** [comment]
I suggest a merge, integers are cheap.

**Comment by dericed** [comment]
nudge, let's update the version before tomorrow's meeting

**Comment by dericed** [comment]
<\_<
\>\_>
bump
:)

**Comment by retokromer** [comment]
>should i still merge this or wait ?

Please merge.

**Comment by michaelni** [comment]
Merged, sorry for the delay, i was busy (and still am a bit) with a heap of random things and i thought i had things in my calendar which it seems i did not :(

**Pull request closed without merging**
